### ISSUE TITLE
Take code cleanup improvement from PowerShell repo

### ISSUE THREAD

**Issue by adityapatwardhan** [PowerShell/MarkdownRender#11]
For details look at comment: 
https://github.com/PowerShell/PowerShell/pull/14090#issuecomment-727154380

**Comment by xtqqczze** [comment]
@adityapatwardhan I can submit PRs here once PowerShell/PowerShell#14090 is merged.

**Comment by adityapatwardhan** [comment]
I would really appreciate it.

**Comment by xtqqczze** [comment]
@adityapatwardhan Please could you look at open PRs.

**Comment by adityapatwardhan** [comment]
Aall code cleanup changes have been merged.
